language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t userprogrammer/docker-react .

script:
  - docker run -e CI=true userprogrammer/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-724667109499"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_ID"
  secret_access_key: "$AWS_SECRET_KEY"
