language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t userprogrammer/docker-react .

script:
  - docker run -e CI=true userprogrammer/docker-react npm run test
