FROM node:alpine

USER 1000

RUN mkdir /home/node/app

WORKDIR /home/node/app

COPY --chown=1000:1000 package.json .

RUN npm install

# This step is not needed, currently, because my `docker run...` command
# creates a volume against the host machine directory that contains all
# the source files.
#COPY . .

CMD npm run start

